version: '3.7'
services:
  rails:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
      args:
        UID: ${UID}
        GID: ${UID}
        INSTALL_PG_CLIENT: ${INSTALL_PG_CLIENT}
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app:cached
      - gems:/gems
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    entrypoint: ./docker/ruby/ruby-entrypoint
    user: ruby
    tty: true
    stdin_open: true
  postgres:
    image: postgres:9.6
    ports:
      - "5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  gems:
