insert into licenses set spdx='AFL-1.2', name='Academic Free License v1.2', created_at=now(), updated_at=now();
insert into licenses set spdx='AFL-2.0', name='Academic Free License v2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='AFL-2.1', name='Academic Free License v2.1', created_at=now(), updated_at=now();
insert into licenses set spdx='AFL-3.0', name='Academic Free License v3.0', created_at=now(), updated_at=now();
insert into licenses set spdx='APL-1.0', name='Adaptive Public License', created_at=now(), updated_at=now();
insert into licenses set spdx='ANTLR-PD', name='ANTLR Software Rights Notice', created_at=now(), updated_at=now();
insert into licenses set spdx='Apache-1.0', name='Apache License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='Apache-1.1', name='Apache License 1.1', created_at=now(), updated_at=now();
insert into licenses set spdx='Apache-2.0', name='Apache License 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='APSL-1.0', name='Apple Public Source License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='APSL-1.1', name='Apple Public Source License 1.1', created_at=now(), updated_at=now();
insert into licenses set spdx='APSL-1.2', name='Apple Public Source License 1.2', created_at=now(), updated_at=now();
insert into licenses set spdx='APSL-2.0', name='Apple Public Source License 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='Artistic-1.0', name='Artistic License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='Artistic-2.0', name='Artistic License 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='AAL', name='Attribution Assurance License', created_at=now(), updated_at=now();
insert into licenses set spdx='BSL-1.0', name='Boost Software License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='BSD-2-Clause', name='BSD 2-clause "Simplified" or "FreeBSD" License', created_at=now(), updated_at=now();
insert into licenses set spdx='BSD-3-Clause', name='BSD 3-clause "New" or "Revised" License', created_at=now(), updated_at=now();
insert into licenses set spdx='BSD-4-Clause', name='BSD 4-clause "Original" or "Old" License', created_at=now(), updated_at=now();
insert into licenses set spdx='CECILL-1.0', name='CeCILL Free Software License Agreement v1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CECILL-2.0', name='CeCILL Free Software License Agreement v2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CECILL-B', name='CeCILL-B Free Software License Agreement', created_at=now(), updated_at=now();
insert into licenses set spdx='CECILL-C', name='CeCILL-C Free Software License Agreement', created_at=now(), updated_at=now();
insert into licenses set spdx='ClArtistic', name='Clarified Artistic License', created_at=now(), updated_at=now();
insert into licenses set spdx='CDDL-1.0', name='Common Development and Distribution License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CPAL-1.0', name='Common Public Attribution License 1.0 ', created_at=now(), updated_at=now();
insert into licenses set spdx='CPL-1.0', name='Common Public License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CATOSL-1.1', name='Computer Associates Trusted Open Source License 1.1', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-1.0', name='Creative Commons Attribution 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-2.0', name='Creative Commons Attribution 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-2.5', name='Creative Commons Attribution 2.5', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-3.0', name='Creative Commons Attribution 3.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-ND-1.0', name='Creative Commons Attribution No Derivatives 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-ND-2.0', name='Creative Commons Attribution No Derivatives 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-ND-2.5', name='Creative Commons Attribution No Derivatives 2.5', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-ND-3.0', name='Creative Commons Attribution No Derivatives 3.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-NC-1.0', name='Creative Commons Attribution Non Commercial 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-NC-2.0', name='Creative Commons Attribution Non Commercial 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-NC-2.5', name='Creative Commons Attribution Non Commercial 2.5', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-NC-3.0', name='Creative Commons Attribution Non Commercial 3.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-NC-ND-1.0', name='Creative Commons Attribution Non Commercial No Derivatives 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-NC-ND-2.0', name='Creative Commons Attribution Non Commercial No Derivatives 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-NC-ND-2.5', name='Creative Commons Attribution Non Commercial No Derivatives 2.5', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-NC-ND-3.0', name='Creative Commons Attribution Non Commercial No Derivatives 3.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-NC-SA-1.0', name='Creative Commons Attribution Non Commercial Share Alike 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-NC-SA-2.0', name='Creative Commons Attribution Non Commercial Share Alike 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-NC-SA-2.5', name='Creative Commons Attribution Non Commercial Share Alike 2.5', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-NC-SA-3.0', name='Creative Commons Attribution Non Commercial Share Alike 3.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-SA-1.0', name='Creative Commons Attribution Share Alike 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-SA-2.0', name='Creative Commons Attribution Share Alike 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-SA-2.5', name='Creative Commons Attribution Share Alike 2.5', created_at=now(), updated_at=now();
insert into licenses set spdx='CC-BY-SA-3.0', name='Creative Commons Attribution Share Alike 3.0', created_at=now(), updated_at=now();
insert into licenses set spdx='CC0-1.0', name='Creative Commons Zero v1.0 Universal', created_at=now(), updated_at=now();
insert into licenses set spdx='CUA-OPL-1.0', name='CUA Office Public License v1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='EPL-1.0', name='Eclipse Public License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='eCos-2.0', name='eCos license version 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='ECL-1.0', name='Educational Community License v1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='ECL-2.0', name='Educational Community License v2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='EFL-1.0', name='Eiffel Forum License v1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='EFL-2.0', name='Eiffel Forum License v2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='Entessa', name='Entessa Public License', created_at=now(), updated_at=now();
insert into licenses set spdx='ErlPL-1.1', name='Erlang Public License v1.1', created_at=now(), updated_at=now();
insert into licenses set spdx='EUDatagrid', name='EU DataGrid Software License', created_at=now(), updated_at=now();
insert into licenses set spdx='EUPL-1.0', name='European Union Public License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='EUPL-1.1', name='European Union Public License 1.1', created_at=now(), updated_at=now();
insert into licenses set spdx='Fair', name='Fair License', created_at=now(), updated_at=now();
insert into licenses set spdx='Frameworx-1.0', name='Frameworx Open License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='AGPL-3.0', name='GNU Affero General Public License v3', created_at=now(), updated_at=now();
insert into licenses set spdx='GFDL-1.2', name='GNU Free Documentation License v1.1', created_at=now(), updated_at=now();
insert into licenses set spdx='GFDL-1.2', name='GNU Free Documentation License v1.2', created_at=now(), updated_at=now();
insert into licenses set spdx='GFDL-1.3', name='GNU Free Documentation License v1.3', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-1.0', name='GNU General Public License v1.0 only', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-1.0+', name='GNU General Public License v1.0 or later', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-2.0', name='GNU General Public License v2.0 only', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-2.0+', name='GNU General Public License v2.0 or later', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-2.0-with-autoconf-exception', name='GNU General Public License v2.0 w/Autoconf exception', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-2-with-bison-exception', name='GNU General Public License v2.0 w/Bison exception', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-2.0-with-classpath-exception', name='GNU General Public License v2.0 w/Classpath exception', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-2.0-with-font-exception', name='GNU General Public License v2.0 w/Font exception', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-2.0-with-GCC-exception', name='GNU General Public License v2.0 w/GCC Runtime Library exception', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-3.0', name='GNU General Public License v3.0 only', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-3.0+', name='GNU General Public License v3.0 or later', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-3.0-with-autoconf-exception', name='GNU General Public License v3.0 w/Autoconf exception', created_at=now(), updated_at=now();
insert into licenses set spdx='GPL-3.0-with-GCC-exception', name='GNU General Public License v3.0 w/GCC Runtime Library exception', created_at=now(), updated_at=now();
insert into licenses set spdx='LGPL-2.1', name='GNU Lesser General Public License v2.1 only', created_at=now(), updated_at=now();
insert into licenses set spdx='LGPL-2.1+', name='GNU Lesser General Public License v2.1or later', created_at=now(), updated_at=now();
insert into licenses set spdx='LGPL-3.0', name='GNU Lesser General Public License v3.0 only', created_at=now(), updated_at=now();
insert into licenses set spdx='LGPL-3.0+', name='GNU Lesser General Public License v3.0 or later', created_at=now(), updated_at=now();
insert into licenses set spdx='LGPL-2.0', name='GNU Library General Public License v2 only', created_at=now(), updated_at=now();
insert into licenses set spdx='LGPL-2.0+', name='GNU Library General Public License v2 or later', created_at=now(), updated_at=now();
insert into licenses set spdx='gSOAP-1.3b', name='gSOAP Public License v1.b', created_at=now(), updated_at=now();
insert into licenses set spdx='HPND', name='Historic Permission Notice and Disclaimer', created_at=now(), updated_at=now();
insert into licenses set spdx='IPL-1.0', name='IBM Public License v1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='IPA', name='IPA Font License', created_at=now(), updated_at=now();
insert into licenses set spdx='ISC', name='ISC License (Bind, DHCP Server)', created_at=now(), updated_at=now();
insert into licenses set spdx='LPPL-1.0', name='LaTeX Project Public License v1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='LPPL-1.1', name='LaTeX Project Public License v1.1', created_at=now(), updated_at=now();
insert into licenses set spdx='LPPL-1.2', name='LaTeX Project Public License v1.2', created_at=now(), updated_at=now();
insert into licenses set spdx='LPPL-1.3c', name='LaTeX Project Public License v1.3c', created_at=now(), updated_at=now();
insert into licenses set spdx='Libpng', name='libpng License', created_at=now(), updated_at=now();
insert into licenses set spdx='LPL-1.02', name='Lucent Public License v1.02 (Plan9)', created_at=now(), updated_at=now();
insert into licenses set spdx='MS-PL', name='Microsoft Public License', created_at=now(), updated_at=now();
insert into licenses set spdx='MS-RL', name='Microsoft Reciprocal License', created_at=now(), updated_at=now();
insert into licenses set spdx='MirOS', name='MirOS Licence', created_at=now(), updated_at=now();
insert into licenses set spdx='MIT', name='MIT license (also X11)', created_at=now(), updated_at=now();
insert into licenses set spdx='Motosoto', name='Motosoto License', created_at=now(), updated_at=now();
insert into licenses set spdx='MPL-1.0', name='Mozilla Public License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='MPL-1.1', name='Mozilla Public License 1.1 ', created_at=now(), updated_at=now();
insert into licenses set spdx='Multics', name='Multics License', created_at=now(), updated_at=now();
insert into licenses set spdx='NASA-1.3', name='NASA Open Source Agreement 1.3', created_at=now(), updated_at=now();
insert into licenses set spdx='Nauman', name='Naumen Public License', created_at=now(), updated_at=now();
insert into licenses set spdx='NGPL', name='Nethack General Public License', created_at=now(), updated_at=now();
insert into licenses set spdx='Nokia', name='Nokia Open Source License', created_at=now(), updated_at=now();
insert into licenses set spdx='NPOSL-3.0', name='Non-Profit Open Software License 3.0', created_at=now(), updated_at=now();
insert into licenses set spdx='NTP', name='NTP License', created_at=now(), updated_at=now();
insert into licenses set spdx='OCLC-2.0', name='OCLC Research Public License 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='ODbL-1.0', name='ODC Open Database License v1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='OGTSL', name='Open Group Test Suite License', created_at=now(), updated_at=now();
insert into licenses set spdx='OSL-1.0', name='Open Software License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='OSL-2.0', name='Open Software License 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='OSL-3.0', name='Open Software License 3.0', created_at=now(), updated_at=now();
insert into licenses set spdx='OLDAP-2.8', name='OpenLDAP Public License v2.8', created_at=now(), updated_at=now();
insert into licenses set spdx='OpenSSL', name='OpenSSL License', created_at=now(), updated_at=now();
insert into licenses set spdx='PHP-3.0', name='PHP License v3.0', created_at=now(), updated_at=now();
insert into licenses set spdx='PostgreSQL', name='PostgreSQL License', created_at=now(), updated_at=now();
insert into licenses set spdx='Python-2.0', name='Python Software Foundation License v2', created_at=now(), updated_at=now();
insert into licenses set spdx='QPL-1.0', name='Q Public License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='RPSL-1.0', name='RealNetworks Public Source License v1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='RPL-1.5', name='Reciprocal Public License 1.5 ', created_at=now(), updated_at=now();
insert into licenses set spdx='RHeCos-1.1', name='Red Hat eCos Public License v1.1', created_at=now(), updated_at=now();
insert into licenses set spdx='RSCPL', name='Ricoh Source Code Public License', created_at=now(), updated_at=now();
insert into licenses set spdx='Ruby', name='Ruby License', created_at=now(), updated_at=now();
insert into licenses set spdx='SAX-PD', name='Sax Public Domain Notice', created_at=now(), updated_at=now();
insert into licenses set spdx='OFL-1.1', name='SIL Open Font License 1.1', created_at=now(), updated_at=now();
insert into licenses set spdx='Simple-2.0', name='Simple Public License 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='Sleepycat', name='Sleepycat License', created_at=now(), updated_at=now();
insert into licenses set spdx='SugarCRM-1.1.3', name='SugarCRM Public License v1.1.3', created_at=now(), updated_at=now();
insert into licenses set spdx='SPL-1.0', name='Sun Public License v1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='Watcom-1.0', name='Sybase Open Watcom Public License 1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='NCSA', name='University of Illinois/NCSA Open Source License', created_at=now(), updated_at=now();
insert into licenses set spdx='VSL-1.0', name='Vovida Software License v1.0', created_at=now(), updated_at=now();
insert into licenses set spdx='W3C', name='W3C Software and Notice License', created_at=now(), updated_at=now();
insert into licenses set spdx='WXwindows', name='wxWindows Library License', created_at=now(), updated_at=now();
insert into licenses set spdx='Xnet', name='X.Net License', created_at=now(), updated_at=now();
insert into licenses set spdx='XFree86-1.1', name='XFree86 License 1.1', created_at=now(), updated_at=now();
insert into licenses set spdx='YPL-1.1', name='Yahoo! Public License v1.1', created_at=now(), updated_at=now();
insert into licenses set spdx='Zimbra-1.3', name='Zimbra Publice License v1.3', created_at=now(), updated_at=now();
insert into licenses set spdx='Zlib', name='zlib License', created_at=now(), updated_at=now();
insert into licenses set spdx='ZPL-1.1', name='Zope Public License 1.1', created_at=now(), updated_at=now();
insert into licenses set spdx='ZPL-2.0', name='Zope Public License 2.0', created_at=now(), updated_at=now();
insert into licenses set spdx='ZPL-2.1', name='Zope Public License 2.1', created_at=now(), updated_at=now();
